# Generated by Django 4.2.2 on 2023-07-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crystal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('mohs_hardness', models.DecimalField(decimal_places=2, max_digits=3)),
                ('usual_color', models.CharField(max_length=250)),
                ('img', models.CharField(max_length=5000)),
                ('finding_place', models.CharField(max_length=9000)),
            ],
            options={
                'verbose_name': 'crystal',
                'verbose_name_plural': 'crystals',
            },
        ),
    ]
