# Generated by Django 4.2.2 on 2023-07-01 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crystal',
            options={'ordering': ['name'], 'verbose_name': 'crystal', 'verbose_name_plural': 'crystals'},
        ),
        migrations.RenameField(
            model_name='crystal',
            old_name='finding_place',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='crystal',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
