# Generated by Django 4.2.2 on 2023-07-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_crystal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crystal',
            name='bio',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
        migrations.AlterField(
            model_name='crystal',
            name='img',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='crystal',
            name='mohs_hardness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='crystal',
            name='usual_color',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
