# Generated by Django 4.2.2 on 2023-07-03 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_crystal_bio_alter_crystal_img_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crystal',
            new_name='CrystalType',
        ),
        migrations.AlterModelOptions(
            name='crystaltype',
            options={'ordering': ['name'], 'verbose_name': 'crystal_type', 'verbose_name_plural': 'crystal_types'},
        ),
    ]
