# Generated by Django 4.2.2 on 2023-07-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_crystal_crystaltype_alter_crystaltype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crystaltype',
            name='bio',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
