# Generated by Django 4.2.2 on 2023-07-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_collection_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crystaltype',
            name='mohs_hardness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
